<!DOCTYPE html>
<html lang="en">


<body>
    <spring:url value="/test.txt" htmlEscape="true" var="springUrl" />

    <p><a href="${springUrl}">URL generated by Spring</a></p>
    <p><a href="${url}">URL generated by JSTL</a></p>
</body>

</html>